#!/bin/bash
echo "Running project \"$1\" through selector [brainbase/bb/br/ss/shkr/shkrmishstore]."
if [ "brainbase" == "$1" ] || [ "br" == "$1" ] || [ "bb" == "$1" ]; then
    echo "Detected query as Brainbase. Running the UI Project."
    if [ "$PWD" != "brainbaseui" ]; then
        cd brainbaseui
    fi
    npm run dev
else
    if [ "shkrmishstore" == "$1" ] || [ "shkr" == "$1" ] || [ "ss" == "$1" ]; then
        echo "Detected query as Shkrmishstore. Running UI Frontend."
        if [ "$PWD" != "shkrmishstore" ]; then
            cd shkrmishstore
        fi
        npm run dev
    else
        echo "No query detected."
        echo "Expected [brainbase/bb/brr] [shkrmishstore/ss/shkr]"
    fi
fi
