export const models = [
    "Counterfeit",
    "Anything v3",
    "Abyss OrangeMix",
    "Hassanblend",
    "ChilloutMix",
    "Experience",
    "Yiffy",
    "Realism Engine",
    "Liberty",
    "Arcane Diffusion",
    "Anygen",
    "Epic Diffusion",
    "Anything Diffusion",
    "iCoMix",
    "Dreamlike Diffusion",
    "URPM",
    "Deliberate",
    "Rev Animated",
    "Pastel Mix",
    "stable_diffusion",
    "GorynichMix",
    "Protogen Infinity",
    "Project Unreal Engine 5",
    "Colorful",
    "Illuminati Diffusion",
    "ProtoGen",
    "CyriousMix",
    "Poison",
    "Woop-Woop Photo",
    "Dreamshaper",
    "Eimis Anime Diffusion",
    "Inkpunk Diffusion",
    "Realistic Vision",
    "Dreamlike Photoreal",
    "FaeTastic",
    "Something",
    "Laolei New Berry Protogen Mix",
    "Kenshi",
    "3DKX",
    "stable_diffusion_2.1",
    "Analog Diffusion",
    "Openniji",
    "Perfect World",
    "Midjourney Diffusion",
    "AbyssOrangeMix-AfterDark",
    "HRL",
    "GuoFeng",
    "RealBiter",
    "Nitro Diffusion",
    "Pretty 2.5D",
    "Zeipher Female Model"
]
export default models;